//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int id { get; set; }
        public long barcode { get; set; }
        public int Wedstrijdid { get; set; }
        public string Persoonid { get; set; }
        public int plaatsId { get; set; }
        public bool Betaald { get; set; }
        public bool Geactiveerd { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Plaats Plaats { get; set; }
        public virtual Wedstrijd Wedstrijd { get; set; }
    }
}
