//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wedstrijd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wedstrijd()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int id { get; set; }
        public int thuisPloeg { get; set; }
        public int bezoekersPloeg { get; set; }
        public int stadionId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Clubs Clubs { get; set; }
        public virtual Clubs Clubs1 { get; set; }
        public virtual Stadion Stadion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
